[workspace]
members = [
    "empa-tk",
    "examples/web/find_runs",
    "examples/web/prefix_sum_exclusive",
    "examples/web/prefix_sum_inclusive",
    "examples/web/radix_sort",
    "examples/web/radix_sort_by",
    "examples/web/scatter_by"
]
