[workspace]
members = [
    "empa-tk",
    "examples/find_runs",
    "examples/gather_by",
    "examples/prefix_sum_exclusive",
    "examples/prefix_sum_inclusive",
    "examples/radix_sort",
    "examples/radix_sort_by",
    "examples/radix_sort_half_precision",
    "examples/scatter_by"
]
