[package]
name = "empa-tk"
version = "0.1.0"
authors = ["RSSchermer <roland0507@gmail.com>"]
edition = "2018"

[dependencies]
empa = { version = "0.1.0", path = "../../glitz/empa", features = ["arwa"] }
zeroable = { path = "../../zeroable_crates/zeroable" }
